# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ride_service_pb2 as ride__service__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ride_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RideServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRide = channel.unary_unary(
                '/ride.RideService/CreateRide',
                request_serializer=ride__service__pb2.RideRequest.SerializeToString,
                response_deserializer=ride__service__pb2.RideResponse.FromString,
                _registered_method=True)
        self.GetRide = channel.unary_unary(
                '/ride.RideService/GetRide',
                request_serializer=ride__service__pb2.RideId.SerializeToString,
                response_deserializer=ride__service__pb2.RideResponse.FromString,
                _registered_method=True)
        self.UpdateRide = channel.unary_unary(
                '/ride.RideService/UpdateRide',
                request_serializer=ride__service__pb2.RideUpdateRequest.SerializeToString,
                response_deserializer=ride__service__pb2.RideResponse.FromString,
                _registered_method=True)


class RideServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RideServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRide': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRide,
                    request_deserializer=ride__service__pb2.RideRequest.FromString,
                    response_serializer=ride__service__pb2.RideResponse.SerializeToString,
            ),
            'GetRide': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRide,
                    request_deserializer=ride__service__pb2.RideId.FromString,
                    response_serializer=ride__service__pb2.RideResponse.SerializeToString,
            ),
            'UpdateRide': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRide,
                    request_deserializer=ride__service__pb2.RideUpdateRequest.FromString,
                    response_serializer=ride__service__pb2.RideResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ride.RideService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ride.RideService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RideService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride.RideService/CreateRide',
            ride__service__pb2.RideRequest.SerializeToString,
            ride__service__pb2.RideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride.RideService/GetRide',
            ride__service__pb2.RideId.SerializeToString,
            ride__service__pb2.RideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride.RideService/UpdateRide',
            ride__service__pb2.RideUpdateRequest.SerializeToString,
            ride__service__pb2.RideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
