# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ride_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ride_service.proto\x12\x04ride\"Y\n\x0bRideRequest\x12\x17\n\x0fpickup_location\x18\x01 \x01(\t\x12\x18\n\x10\x64ropoff_location\x18\x02 \x01(\t\x12\x17\n\x0fpassenger_count\x18\x03 \x01(\x05\"h\n\x0cRideResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\x12\x12\n\nvehicle_id\x18\x03 \x01(\t\x12 \n\x06status\x18\x04 \x01(\x0e\x32\x10.ride.RideStatus\"\x19\n\x06RideId\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\"F\n\x11RideUpdateRequest\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.ride.RideStatus*9\n\nRideStatus\x12\x0b\n\x07PENDING\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x32\xb0\x01\n\x0bRideService\x12\x35\n\nCreateRide\x12\x11.ride.RideRequest\x1a\x12.ride.RideResponse\"\x00\x12-\n\x07GetRide\x12\x0c.ride.RideId\x1a\x12.ride.RideResponse\"\x00\x12;\n\nUpdateRide\x12\x17.ride.RideUpdateRequest\x1a\x12.ride.RideResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ride_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RIDESTATUS']._serialized_start=324
  _globals['_RIDESTATUS']._serialized_end=381
  _globals['_RIDEREQUEST']._serialized_start=28
  _globals['_RIDEREQUEST']._serialized_end=117
  _globals['_RIDERESPONSE']._serialized_start=119
  _globals['_RIDERESPONSE']._serialized_end=223
  _globals['_RIDEID']._serialized_start=225
  _globals['_RIDEID']._serialized_end=250
  _globals['_RIDEUPDATEREQUEST']._serialized_start=252
  _globals['_RIDEUPDATEREQUEST']._serialized_end=322
  _globals['_RIDESERVICE']._serialized_start=384
  _globals['_RIDESERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
