# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64river_service.proto\x12\x06\x64river\"\x89\x01\n\x19\x44riverRegistrationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\x14\n\x0cvehicle_type\x18\x04 \x01(\t\x12#\n\x1bvehicle_registration_number\x18\x05 \x01(\t\"/\n\x1a\x44riverRegistrationResponse\x12\x11\n\tdriver_id\x18\x01 \x01(\t\"A\n\x19\x44riverAvailabilityRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x11\n\tavailable\x18\x02 \x01(\x08\"B\n\x1a\x44riverAvailabilityResponse\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x11\n\tavailable\x18\x02 \x01(\x08\"\x1d\n\x08\x44riverId\x12\x11\n\tdriver_id\x18\x01 \x01(\t\"\x91\x01\n\x0e\x44riverResponse\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x14\n\x0cvehicle_type\x18\x05 \x01(\t\x12#\n\x1bvehicle_registration_number\x18\x06 \x01(\t2\x88\x02\n\rDriverService\x12Y\n\x0eRegisterDriver\x12!.driver.DriverRegistrationRequest\x1a\".driver.DriverRegistrationResponse\"\x00\x12\x63\n\x18UpdateDriverAvailability\x12!.driver.DriverAvailabilityRequest\x1a\".driver.DriverAvailabilityResponse\"\x00\x12\x37\n\tGetDriver\x12\x10.driver.DriverId\x1a\x16.driver.DriverResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVERREGISTRATIONREQUEST']._serialized_start=33
  _globals['_DRIVERREGISTRATIONREQUEST']._serialized_end=170
  _globals['_DRIVERREGISTRATIONRESPONSE']._serialized_start=172
  _globals['_DRIVERREGISTRATIONRESPONSE']._serialized_end=219
  _globals['_DRIVERAVAILABILITYREQUEST']._serialized_start=221
  _globals['_DRIVERAVAILABILITYREQUEST']._serialized_end=286
  _globals['_DRIVERAVAILABILITYRESPONSE']._serialized_start=288
  _globals['_DRIVERAVAILABILITYRESPONSE']._serialized_end=354
  _globals['_DRIVERID']._serialized_start=356
  _globals['_DRIVERID']._serialized_end=385
  _globals['_DRIVERRESPONSE']._serialized_start=388
  _globals['_DRIVERRESPONSE']._serialized_end=533
  _globals['_DRIVERSERVICE']._serialized_start=536
  _globals['_DRIVERSERVICE']._serialized_end=800
# @@protoc_insertion_point(module_scope)
